### ISSUE TITLE
LinkDown is not compatible with MacOS

### ISSUE THREAD

**Issue by ZigaoWang** [LinkScapeOfficial/LinkDown#6]
# Issue: LinkDown is not compatible with MacOS
I discovered that LinkDown is only compatible with Windows, since in the demo it requires cmd (which is not available on MacOS). I wonder if there will ever be a MacOS version or please be sure to claim in your README file that your product is only available to Windows user. Thank you very much!

**Comment by TakumiBC** [comment]
HI Zigao!
LinkDown could be compatible with MacOS, however, it's because the commands needed to be sent to the system terminal / cmd is totally different. There is a way to solve it, but I suggest you can just use Downie (Which is what I currently use).
If you really want to use LinkDown on mac, you will have to modify the browser extension to send only URLs instead of commands to the NativeHost, and make two different NativeHosts on Windows and MacOS. Finally, you will need to make a set-up script that installs yt-dlp, you-get and ffmpeg automatically, set up the `$PATH`, and add nativehost to the place that the browser identifies.

(P.S. I saw the green tie on your GitHub avatar and saw you are also in Shanghai. Are you in YK Pao School? I used to be in YK Pao during Grade 1 to 6)

**Comment by TakumiBC** [comment]
@ZigaoWang

**Comment by ZigaoWang** [comment]
Hi Thomas!

First of all, thanks for the suggestion! I am currently using Downie 4 for downloading videos. It certainly is a great app!

Yes, I am in YK Pao School and I had heard you from one of my friends, and she said you were skilled at making backend programming stuff (correct me if wrong). Therefore, I went to search you on GitHub and found you! By the way, I'm a frontend developer (which make static HTML websites), so I'm not good that these stuff.

Anyways, keep up the good work! I believe your team LinkScape can achieve something big in the future!

Best Regards,
[Zigao Wang](https://zigaow.com)

**Comment by ZigaoWang** [comment]
Hey Thomas! I love you
@TakumiBC
